# Nível 1 - Disparo manual

name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando dependências com npm
        run: npm install

    # executando testes e2e
      - name: Executando testes com mocha
        run: npm run test:report
        
      - name: Verificar se o relatório é gerado
        run: ls -R reports || echo "Relatório não encontrado"

      - name: Upload relatório gerado em mochawesome
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: reports/mochawesome
